### ISSUE TITLE
Mobile Commons integration - *Priority 3*

### ISSUE THREAD

**Issue by angaither** [DoSomething/aurora#10]
Helpful?

**Comment by mshmsh5000** [comment]
Yes

**Comment by mshmsh5000** [comment]
To be clear, the first iteration of this will involve directly accessing the Mobile Commons API to display related user data.

**Comment by jonuy** [comment]
Info on the Mobile Commons endpoint for getting user info: https://mobilecommons.zendesk.com/hc/en-us/articles/202052534-REST-API#ProfileSummary
