### ISSUE TITLE
MobileCommons messages opt_in link

### ISSUE THREAD

**Issue by antonhalim** [DoSomething/aurora#108]
To be able to provide a link to Mobile Commons to see which opt in action that triggers messages to be sent from DS MobileCommons service to users. ex `https://secure.mcommons.com/campaigns/{campaign_id}/opt_in_paths/{opt_in_path_id}`

So we are able to accomodate a better responsive and logical MC service to users.

@uy will be the right person to ask or add more info here

**Comment by DFurnes** [comment]
Closing this, since we're holding off on Mobile Commons API integration for now.
