### ISSUE TITLE
Delete api keys 

### ISSUE THREAD

**Issue by angaither** [DoSomething/aurora#23]
Create a `delete` api key functionality in the admin ui

**Comment by mshmsh5000** [comment]
Wait, don't delete API keys.

**Comment by mshmsh5000** [comment]
Thanks @angaither

**Comment by aaronschachter** [comment]
We need the ability to at least disable keys though, [for things like](https://github.com/aaronschachter/LetsDoThis-iOS/commit/752180c137e9ac2eeb6165dd6576259f9897d941)

**Comment by jonuy** [comment]
Related: https://github.com/DoSomething/northstar/issues/225

**Comment by DFurnes** [comment]
This is now possible through Northstar's API. Documentation is [in the wiki](https://github.com/DoSomething/northstar/wiki/Spec#deleting-an-api-key).

**Comment by angaither** [comment]
sweeeeet @DFurnes do we want to allow this via aurora as well?

**Comment by DFurnes** [comment]
Yes, that's the plan!
