### ISSUE TITLE
User detail page

### ISSUE THREAD

**Issue by angaither** [DoSomething/aurora#33]
this might be a new addition to neue, since there isn't a lot form patterns in neue yet. 

@DFurnes can provide more detail here

**Comment by angaither** [comment]
Campaign info will be displayed on this page as well, and it can follow the [duo-gallery with figures inside it pattern](http://neue.dosomething.org/#gallery-duo)

**Comment by paulhan221** [comment]
closed with #42

**Comment by paulhan221** [comment]
closed with #42
