### ISSUE TITLE
Make form fields appear inactive

### ISSUE THREAD

**Issue by angaither** [DoSomething/aurora#61]
On the user edit page, fields `mongo_id` and `drupal_id` should be inactive form fields
Neue might not have a style for this (cc @DFurnes)

**Comment by DFurnes** [comment]
There aren't styles in Neue at the moment, but if you add `disabled` attribute to the form field the browser will handle the behavior aspect of disabling those fields.

**Comment by paulhan221** [comment]
Oh whoops, I accidentally hit close issue. But the fields for Mongo Id and Drupal UID do have a "disabled => true" on them so you cant edit them =]

**Comment by angaither** [comment]
Apologies, yeah, I see that they are disabled, so this issue should be fixed when DoSomething/neue/issues/512 is resolved.

**Comment by DFurnes** [comment]
Closing, since this has been fixed! :hammer:
